name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build the Docker image
        run: docker build . --tag deduard/tools:cloudflare-dns-ip-updater-$(date +%Y%m%d)
      - name: Publish Docker image
        run: docker push deduard/tools:cloudflare-dns-ip-updater-$(date +%Y%m%d)
