name: Docker Image CD

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: Build Docker image
        run: docker buildx build --push -t deduard/tools:cloudflare-dns-ip-updater-$(date +%Y%m%d) -t deduard/tools:cloudflare-dns-ip-updater-latest --platform linux/amd64,linux/arm/v7,linux/arm64 . --rm
