name: Merge or push to main workflow

on:

  workflow_dispatch:

  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  checkout:
    name: Build and push Docker image
    runs-on: self-hosted
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

  build-image:
    name: Build and push Docker image
    needs: [checkout]
    uses: ./.github/workflows/docker-build-push.yml
    with:
      docker_tags: deduard/tools:cloudflare-dns-ip-updater-${{ needs.checkout.outputs.date }}