name: PR CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
