name: Create Github release

on:
  push:
    tags: [v*]

jobs:
  release-notes:
    name: Create Release Notes
    runs-on: self-hosted
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: gen_release_notes
        run: |
          # Bash script to generate release notes
          # Fetch commit messages and construct release notes text
          echo "Release Notes:" > release_notes.md
          echo "Docker Images:" >> release_notes.md
          echo "https://hub.docker.com/r/deduard/tools/tags?page=1&name=cloudflare-dns-ip-updater" >> release_notes.md
          # Command to get commit messages
          # git log $(git describe --tags --abbrev=0)..HEAD --oneline >> release_notes.md
          # Replace above command with your logic to fetch commit messages
          echo "notes=$(cat release_notes.md)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.gen_release_notes.outputs.notes }}
          generate_release_notes: true

  build-image:
    name: Build and push Docker image
    needs: [release-notes]
    uses: ./.github/workflows/docker-build-push.yml
    with:
      docker_tags: deduard/tools:cloudflare-dns-ip-updater-${{ needs.release-notes.outputs.date }},deduard/tools:cloudflare-dns-ip-updater-latest
    secrets: inherit